### ISSUE TITLE
config.ini issues with write permissions

### ISSUE THREAD

**Issue by jerdra** [pnlbwh/dMRIharmonization#12]
Hi, we're using the harmonization pipeline retrospectively on our data and would like to integrate it into our lab compute system for people in our lab to use easily. The pipeline build will be in a folder where users will only have read/execute permissions. This causes issues when trying to write into lib/config.ini in `harmonization.py` since all users in the lab have read/execute permissions but not write.

Are there plans to allow for config to be written to somewhere else other than lib/config.ini? This would be helpful for storing the config file with the outputs (so people know what the data was run with) and with our current issue.

I'd be more than happy to submit a PR with changes to implement a possible `--config` flag if you would like

Thanks!

**Comment by jerdra** [comment]
i see that #10 addresses this issue!

**Comment by tashrifbillah** [comment]
As you noticed, I have already fixed this issue. I shall make a release in a week.

**Comment by tashrifbillah** [comment]
PR #10
