### ISSUE TITLE
NODDI harmonization

### ISSUE THREAD

**Issue by fedemoro** [pnlbwh/dMRIharmonization#17]
If I'm correct harmonization.py can be used also for multi-shell acquisition (i.e. NODDI). Do I need to specify any value in the --bvalMap for multi-shell data?

Thanks

Fede

**Comment by tashrifbillah** [comment]
Hi @fedemoro, multi-shell harmonization is not available with the current design. However, the algorithm remains same. We are designing multi-shell harmonization so a user doesn't have to manually extract the shells and bind them together after harmonization. It should be available in three weeks from now.

Here is the feature request #11 .
