### ISSUE TITLE
Run the harmonization on more than 2 sites? 

### ISSUE THREAD

**Issue by ddallmeier** [pnlbwh/dMRIharmonization#18]
Is there an option to run the harmonization on multiple target sites at the same time? Or is it necessary to run each pair individually?

**Comment by tashrifbillah** [comment]
> Is there an option to run the harmonization on multiple target sites at the same time?

The program won't do it for your automatically.

> Or is it necessary to run each pair individually?

Yes, yet see explanation below:

It is possible to have one reference site but multiple target sites. This [branch](https://github.com/pnlbwh/dMRIharmonization/tree/warped-in-template) is designed to take into account the above use case. Still, you have to create different templates for each pair of reference-target sites. Just provide different names to `--template` argument i.e `--template firstPair`, `--template secondPair`, ... and it will organize the templates accordingly. Then you can harmonize different sites providing the proper template directory.

You can get the branch as follows:

```
cd dMRIharmonization
git pull origin
git checkout warped-in-template
```

However, if you think your template created using only one pair of reference-target1 sites represents the characteristics of the rest of the target sites i.e. `reference-target1` , `reference-target2`, ... there is nothing stopping you from harmonizing multiple target sites using the scale maps obtained from the first pair. Just run `./harmonization --process ...` multiple times.

Did I answer your question?
