### ISSUE TITLE
Site harmonization issue

### ISSUE THREAD

**Issue by fedemoro** [pnlbwh/dMRIharmonization#19]
I have run the harmonization.py on 26 (ref) 16 (tar) age-match healthy controls. After harmonization the ref site differs more from the ref cite than that before harmonization. 
Printing statistics:
REF mean FA:  0.4764179896357986
TAR mean FA before harmonization:  0.45825602725158743
TAR mean FA after harmonization:  0.5094364786748963

1) Checking the scale maps I notice that they look quite different form the one you show https://github.com/pnlbwh/dMRIharmonization/blob/dipy-dti/doc/flowchart.png since only the bounders of the brain have been scaled. Could you please comment this?
![image](https://user-images.githubusercontent.com/29942574/64602365-f6d65780-d3be-11e9-838f-050d24bf49db.png)

2) in the printing statistics only the man value is reported but not the standard deviation i'm wondering if there is a quick way to extract individual mean FA for each  subject? This could help to see whether there is any issue at the single subject level

Thanks

Fede

**Comment by tashrifbillah** [comment]
Hi @fedemoro ,

Before I address your issues, can you do the following and tell me which branch are you working on?
```
cd dMRIharmonization
git status
```

**Comment by fedemoro** [comment]
Baranch duoy-dti 
the branch is updated in regard to 'origin/dipy-dti'. 

Fede 

Da: "Tashrif Billah" <notifications@github.com> 
A: "pnlbwh/dMRIharmonization" <dMRIharmonization@noreply.github.com> 
Cc: "Federico Moro" <federico.moro@marionegri.it>, "Mention" <mention@noreply.github.com> 
Inviato: Martedì, 10 settembre 2019 15:06:28 
Oggetto: Re: [pnlbwh/dMRIharmonization] Site harmonization issue (#19) 



Hi [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Ffedemoro&e=64908489&h=5584c0a6&f=y&p=y | @fedemoro ] , 

Before I address your issues, can you do the following and tell me which branch are you working on? 
cd dMRIharmonization
git status 


— 
You are receiving this because you were mentioned. 
Reply to this email directly, [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fpnlbwh%2FdMRIharmonization%2Fissues%2F19%3Femail_source%3Dnotifications%26email_token%3DAHEOGLQXRPVLBCQ7R7KGBBTQI6LVJA5CNFSM4IVFJ7S2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6LAKNA%23issuecomment-529925428&e=64908489&h=4790cb4f&f=y&p=y | view it on GitHub ] , or [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHEOGLRPQIPBI6RLS2A3M73QI6LVJANCNFSM4IVFJ7SQ&e=64908489&h=11ed0a27&f=y&p=y | mute the thread ] . 

<html>
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">  </head>
<body>
<br>
<hr>
<div align='center'>
<font face="arial" size="2px" color="#151B8D">L'Istituto di Ricerche Farmacologiche Mario Negri IRCCS desidera
ringraziare tutti i donatori che hanno devoluto il loro 5 per mille - e ci auguriamo vorranno continuare a farlo in futuro - a sostegno
della nostra attivit&#224; e assicurare loro che tutto quanto ricevuto sar&#224; esclusivamente impiegato per le nostre 

ricerche.<br><br>
<b>Ricordiamo di firmare ed indicare il nostro codice fiscale</b>
<div STYLE="Color:red; font-family:Arial; font-size:22px; font-weight:bold"><center>03254210150</center></div>
<b>nel riquadro "Finanziamento agli enti della ricerca scientifica e dell'universit&#224;</b>"<br><br>
Per maggiori informazioni:<BR><BR>Istituto di Ricerche Farmacologiche Mario Negri IRCCS, Via Mario Negri 2 - 20156
Milano<BR>Tel: +39 02 390141 - Fax: +39 02 3546277 +39 02 39001918<BR>Internet:
<A href="http://www.marionegri.it">www.marionegri.it</A>, <A href="mailto:mnegri@marionegri.it">mnegri@marionegri.it</A>
</font>
</div>
<hr>
</body>
</html>

**Comment by tashrifbillah** [comment]
Thanks, did you use `--resample M x N x O` as part of the results you mentioned above?

https://github.com/pnlbwh/dMRIharmonization#3-resampling

**Comment by tashrifbillah** [comment]
In other words, do you know if your subjects across reference and target sites have different spatial resolution that necessitates resampling to a common resolution?

You can check spatial resolution using a command like below:

> fslhd /my/nifti/image | grep pixdim

The following are spatial resolutions found from the above command:

```
pixdim1        1.500000
pixdim2        1.500000
pixdim3        1.500000
```

**Comment by fedemoro** [comment]
No I haven't use the --resample flag since all the subjects in the study have a pixdim of 2x2x2

**Comment by tashrifbillah** [comment]
> i'm wondering if there is a quick way to extract individual mean FA for each subject

I shall implement your suggestion. In the meantime, you can edit `harmonization.py` with 
the following two lines after [this](https://github.com/pnlbwh/dMRIharmonization/blob/spm-bspline/lib/harmonization.py#L336) :

```
print(f'std of all FA: ', np.std(ref_mean))
print(f'all FA: ', ref_mean)
```

Do the same for `target_mean_before` and `target_mean_after`.


Finally, you can extract individual FA at a later time using:

> lib/tests/fa_skeleton_test.py -i /path/to/single_case.txt -s BSNIP -t /path/to/BSNIP/template/

while `single_case.txt` contains only one line like following:

> /path/to/FA/img/whose/meanFA/needs/to/be/computed

**Comment by tashrifbillah** [comment]
> since only the bounders of the brain have been scaled. Could you please comment this?

Reference to your screenshot, if you adjust contrast on `fslview`, you should be able to see values all over the brain, not just the skull region as it is apparent in your screenshot. The scales are within `0-10`, ideally less than `2.5`. So, with default contrast, they may not be visible. On the other hand, I agree the skull scale values can be larger than that of inner-brain scale values. This is due to the division performed [here](https://github.com/pnlbwh/dMRIharmonization/blob/dipy-dti/lib/buildTemplate.py#L185):

```
    scale= ref/(target+eps)
    scale.clip(min=0., out=scale)
    # scale.clip(max=10., min= 0., out= scale)
```

The clipping is in effect in our later commits. However, the high scaling in the skull region is corrected by the algorithm [here](https://github.com/pnlbwh/dMRIharmonization/blob/dipy-dti/lib/cleanOutliers.py#L116), which is a local median filtering approach to remove high values:

```
            mask= findLargestConnectMask(img, mask)

            se= custom_spherical_structure(n_zero)
            paddedMask= np.pad(mask, n_zero, 'constant', constant_values= 0.)

            dilM = binary_dilation(paddedMask, se)*1
            eroM = binary_erosion(paddedMask, se)*1
            skullRingMask = dilM - eroM

        paddedImg = np.pad(img, n_zero, 'constant', constant_values=0.)
        skullRing= paddedImg*skullRingMask
        thresh= np.percentile(skullRing[skullRing>0], 95)
        outLier= (skullRing>thresh)*1
        tmp= local_med_filter(paddedImg, outLier)
        denoisedImg = tmp[n_zero:-n_zero, n_zero:-n_zero, n_zero:-n_zero]

```

**Comment by fedemoro** [comment]
Thanks a lot for clarifying this. 

Coming back to the poor harmonization outcome that I got.

these are the command that I used to create the template
harmonization.py --template path_to/template/ --ref_list ref_.txt --tar.txt --ref_name REF --tar_name TAR --nshm 6 --nproc 4  --debug --create

Not sure whether having omitted --nzero and --denoise flags or the fact that  I've used Raw DWI images before eddy correction my have decreased the quality of template creation.

Do you have any suggestion on what to do to improve it?

**Comment by tashrifbillah** [comment]
1.
> these are the command that I used to create the template

The command looks fine. You are running basic dMRIharmonization. If you had used `--resample MxNxO`, then I would tell you to run `spm-bspline` branch which leverages on a better bspline interpolation method for resampling.

2. 
However, we should definitely do axis alignment and eddy correction before running harmonization. Doing that should yield much better results. I shall make a note in our README about it anyway. If you don't have access to tools for them, you can use our pipeline, specifically the following two scripts:

https://github.com/pnlbwh/pnlNipype/blob/master/scripts/align.py
https://github.com/pnlbwh/pnlNipype/blob/master/scripts/pnl_eddy.py

3. 
The other suggestion would be, to uncomment the [line](https://github.com/pnlbwh/dMRIharmonization/blob/dipy-dti/lib/buildTemplate.py#L187) so scale maps are clipped at 10. :

`# scale.clip(max=10., min= 0., out= scale)`

4. 
Finally, I think you mean the numbers only:

> After harmonization the ref site differs more from the ref cite than that before harmonization

 Although you may find a little discrepancy in the numbers, visual observation should imply goodness of dMRIharmonization. In any case, let us know your progress.

**Comment by fedemoro** [comment]
> > i'm wondering if there is a quick way to extract individual mean FA for each subject
> 
> I shall implement your suggestion. In the meantime, you can edit `harmonization.py` with
> the following two lines after [this](https://github.com/pnlbwh/dMRIharmonization/blob/spm-bspline/lib/harmonization.py#L336) :
> 
> ```
> print(f'std of all FA: ', np.std(ref_mean))
> print(f'all FA: ', ref_mean)
> ```
> 
> Do the same for `target_mean_before` and `target_mean_after`.
> 
> Finally, you can extract individual FA at a later time using:
> 
> > lib/tests/fa_skeleton_test.py -i /path/to/single_case.txt -s BSNIP -t /path/to/BSNIP/template/
> 
> while `single_case.txt` contains only one line like following:
> 
> > /path/to/FA/img/whose/meanFA/needs/to/be/computed

Just a clarification about the mean FA value that is generated. Is it referred to the white matter or to the whole brain?

**Comment by tashrifbillah** [comment]
Hi @fedemoro ,

It's on the skeleton only. Refer to [Debugging](https://github.com/pnlbwh/dMRIharmonization#debugging) section in README.md:

> once the data are in MNI space, we calculate mean FA over the IITmean_FA_skeleton.nii.gz

**Comment by tashrifbillah** [comment]
All FA, mean FA, and std FA are printed:

https://github.com/pnlbwh/dMRIharmonization/issues/27
