### ISSUE TITLE
 MATLAB Runtime Compiler

### ISSUE THREAD

**Issue by fedemoro** [pnlbwh/dMRIharmonization#25]
I already have matlab/R2017a. I suppose I don't have to instal the compiler, but when i try to run pipeline_test.sh i got this error:
subprocess.CalledProcessError: Command '['/rdsgpfs/general/user/fmoro/home/unring/fsl/new/dMRIharmonization/lib/spm_bspline_exec/bspline connectom/B/dwi_B_connectom_st_b1200']' returned non-zero exit status 127.

Do you have any suggestion

many thanks

Fede

**Comment by tashrifbillah** [comment]
You should not need to install MATLAB Runtime Compiler again. However, you still need to edit your `LD_LIBRARY_PATH` as mentioned [here](https://github.com/pnlbwh/dMRIharmonization/blob/spm-bspline/README.md#matlab-runtime-compiler):

Replace `/path/to/v92` with `/path/to/MATLAB/2017a`.
