### ISSUE TITLE
pipeline_test.sh 

### ISSUE THREAD

**Issue by fedemoro** [pnlbwh/dMRIharmonization#26]
I'm trying to test the pipeline (pipeline_test.sh) but I get the error below. 
The environment is set with these executables: antsMultivariateTemplateConstruction2.sh; antsApplyTransforms; antsRegistrationSyNQuick.sh; unring.a64

```
Computing shm_coeff of  prisma/C/dwi_C_prisma_st_b1200_resampled.nii.gz
/bin/sh: /rds/general/user/fmoro/home/unring_new/fsl/dMRIharmonization/lib/antsMultivariateTemplateConstruction2.sh: No such file or directory
Traceback (most recent call last):
  File "../../harmonization.py", line 405, in <module>
    pipeline.run()
  File "/rds/general/user/fmoro/home/miniconda3/envs/harmonization/lib/python3.7/site-packages/plumbum/cli/application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "../../harmonization.py", line 395, in main
    self.createTemplate()
  File "../../harmonization.py", line 214, in createTemplate
    antsMult(os.path.abspath(antsMultCaselist), self.templatePath)
  File "/rds/general/user/fmoro/home/unring_new/fsl/dMRIharmonization/lib/buildTemplate.py", line 97, in antsMult
    caselist]), shell= True)
  File "/rds/general/user/fmoro/home/miniconda3/envs/harmonization/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/rds/general/user/fmoro/home/unring_new/fsl/dMRIharmonization/lib/antsMultivariateTemplateConstruction2.sh -d 3 -g 0.2 -k 2 -t BSplineSyN[0.1,26,0] -r 1 -c 2 -j 32 -f 8x4x2x1 -o ./template/ /rds/general/user/fmoro/home/unring_new/fsl/dMRIharmonization/lib/tests/connectom_prisma/template/antsMultCaselist.txt' returned non-zero exit status 127.
```

**Comment by tashrifbillah** [comment]
Which branch are you working on? The error is up there:

> /bin/sh: /rds/general/user/fmoro/home/unring_new/fsl/dMRIharmonization/lib/antsMultivariateTemplateConstruction2.sh: No such file or directory

**Comment by tashrifbillah** [comment]
`dipy-dti` branch won't look for `dMRIharmonization/lib/antsMultivariateTemplateConstruction2.sh`. Rather, it will use ANTs provided `antsMultivariateTemplateConstruction2.sh`. The difference is, we specified random seed for reproduciblity of template in the former. Again, the former appears in branches `spm-bspline` or later. 

My understanding is, your local branches are out of sync. Try `git pull origin` so your local branches are synced with our development.

**Comment by tashrifbillah** [comment]
If there is more problem, feel free to reopen the issue.
