### ISSUE TITLE
Unable to create conda environment

### ISSUE THREAD

**Issue by SenthilCaesar** [pnlbwh/dMRIharmonization#3]
(base) bash-4.2$ conda --version
conda 4.5.12
(base) bash-4.2$ conda create -f /home/sq566/dMRIharmonization/environmnet.yml

CondaValueError: either -n NAME or -p PREFIX option required,
try "conda create -h" for more details

**Comment by tashrifbillah** [comment]
Sorry, can you try:

`conda env create -f environment.yml`

We are missing the `env` here.

**Comment by tashrifbillah** [comment]
Fixed typo https://github.com/pnlbwh/dMRIharmonization/commit/e66144fb65b064939826bbe9a690fb1a1b22ab0f
