### ISSUE TITLE
path in a line 194 in README.md

### ISSUE THREAD

**Issue by kcho** [pnlbwh/dMRIharmonization#41]
line 194 in README.md states

```
echo "/path/to/v92/runtime/glnxa64:/path/to/v92/bin/glnxa64:/path/to/v92/sys/os/glnxa64:/path/to/v92/opengl/lib/glnxa64:" > env.sh
```

`opengl` is under `/path/to/v95/sys` at least for v95.

**Comment by tashrifbillah** [comment]
I see the error, the last path should be `/path/to/v92/sys/opengl/lib/glnxa64`.

The instruction is copied directly from MATLAB Runtime installation. If you had installed it recently, did it suggest the above or am I the one made a typo? I remember having to correct the default suggestion though.

**Comment by tashrifbillah** [comment]
Fixed by https://github.com/pnlbwh/dMRIharmonization/commit/3481ea7aabb17cd048abbfeb4a4707fc7a54d211
