### ISSUE TITLE
Expected meanFAstats.txt from the pipeline_test.sh

### ISSUE THREAD

**Issue by kcho** [pnlbwh/dMRIharmonization#45]
In `lib/tests/pipeline_test.sh`, the lines that call `fa_skeleton_test.py` appends stats to `${templatePath}/meanFAstat.txt`.

https://github.com/pnlbwh/dMRIharmonization/blob/3b0a48612c31408daa06eb337509ecfdbeddb1f4/lib/tests/pipeline_test.sh#L119-L127

It would be nice to have the **expected** `meanFAstats.txt` from calling `lib/tests/pipeline_test.sh`, so users could compare their test outputs to the **expected** outputs. Or do you already have this text file saved somewhere in your repository?

**Comment by tashrifbillah** [comment]
> It would be nice to have the expected meanFAstats.txt from calling lib/tests/pipeline_test.sh

There is none, the stats are dependent on study. See [here](https://github.com/pnlbwh/dMRIharmonization#debugging) to know how would the values look like.

**Comment by kcho** [comment]
The stats from `lib/tests/pipeline_test.sh` uses the same set, which is downloaded from the repository.

https://github.com/pnlbwh/dMRIharmonization/blob/3b0a48612c31408daa06eb337509ecfdbeddb1f4/lib/tests/pipeline_test.sh#L42

I thought the outputs from `lib/test/pipeline_test.sh` should be consistent for every run. Please correct me if this is wrong.

**Comment by tashrifbillah** [comment]
The expected values are given [here](https://github.com/pnlbwh/dMRIharmonization#1-pipeline).

**Comment by tashrifbillah** [comment]
Please see https://github.com/pnlbwh/dMRIharmonization/tree/fix-force#1-pipeline :)
