### ISSUE TITLE
data harmonization in TBI patients

### ISSUE THREAD

**Issue by fedemoro** [pnlbwh/dMRIharmonization#56]
I need to harmonize data form TBI patients. Some of them have brain contusions and swelling. 
Do you have any idea on how the harmonization works in pathological condition where you have brain distortion?

**Comment by yrathi** [comment]
Thank you for the interest and the question. Currently, we are not supporting harmonization of highly deformed brain anatomy. However, work is under-way for this specific scenario, although we don't have a timeline on when it will be available.
