### ISSUE TITLE
installation problem: unring won't run: can't find fftw

### ISSUE THREAD

**Issue by AndrewDDavis** [pnlbwh/dMRIharmonization#6]
I'm attempting to follow the installation instructions. After cloning `reisert/unring.git`, the binary (unring.a64) seems to expect to find and fftw library, but can't:

> error while loading shared libraries: libfftw3.so.3: cannot open shared object file: No such file or directory

Do you know where I can get this file to install on the cluster? I've tried compiling FFTW from fftw.org, but it only produces libfftw3.a and libfftw3.la in the lib dir.

**Comment by tashrifbillah** [comment]
> Do you know where I can get this file to install on the cluster?

What is your cluster here?

If you are working on RedHat/Centos environment, try:

> sudo yum install fftw-devel

**Comment by tashrifbillah** [comment]
By the way, did you do the following:

```
git clone https://github.com/pnlbwh/dMRIharmonization.git
cd dMRIharmonization
git checkout dipy-dti
```

Sorry, we didn't release the `master` branch yet.

**Comment by AndrewDDavis** [comment]
It's a big cluster that I don't have sudo privelidges on, but I was able to get it to run by copying the file from a debian box and adding the path to LD_LIBRARY_PATH. 

Thanks for the tip on the checkout line, but I think it was already there -- git said, `Already on 'dipy-dti'`.

**Comment by tashrifbillah** [comment]
Eventually I was going to suggest LD_LIBRARY_PATH. Glad that you sorted out the issue already.
