### ISSUE TITLE
Missing Scale_L4

### ISSUE THREAD

**Issue by peterN908** [pnlbwh/dMRIharmonization#68]
Hi there :)

When I run the **./pipeline_test.sh** on the branch **'origin/spm-bspline'** with N_shm = 6 I receive the following error:

` file xxx/dMRIharmonization/lib/tests/connectom_prisma/template/Scale_L4.nii.gz does not exist . `

Would you have any tips in debugging this?

FYI; if i re-run the pipeline_test.sh with N_shm = 2 I do not get this issue

**Comment by peterN908** [comment]
Is it that the number of gradient directions on the test data is insufficient to support N_shm > 2?

**Comment by tashrifbillah** [comment]
Hi @peterN908 ,

> Is it that the number of gradient directions on the test data is insufficient

Yes.

I included [a table](https://github.com/pnlbwh/dMRIharmonization#order-of-spherical-harmonics) in our documentation describing the numbers. Tests are for quick checking only, so I released a data with 13 non-diffusion weighted gradients, which forces `N_shm` to be 2.


> When I run the ./pipeline_test.sh on the branch 'origin/spm-bspline' with N_shm = 6

Curious, how do you do that? I do not provide a way to set up `N_shm` manually as part of `./pipeline_test.sh`.

**Comment by peterN908** [comment]
Thanks for your help
I hard coded in the n_shm because the config file could not be found (similar issue to https://github.com/pnlbwh/dMRIharmonization/issues/65)

**Comment by tashrifbillah** [comment]
>  the config file could not be found

That I can try to solve. So you tried `./pipeline_test.sh` as it is and it complained about the inexistence?

**Comment by peterN908** [comment]
Yes exactly

I checked the /TMP/ folder and the config files being created certainly do exist

**Comment by tashrifbillah** [comment]
Thanks for reporting, I shall try to reproduce at my end.

**Comment by tashrifbillah** [comment]
With `./pipeline_test.sh`, the issue could not be reproduced. Regardless, feel free to switch to the master branch. That employs `tempfile.gettempdir` method to write the configuration to a tempfile.
