### ISSUE TITLE
Harmonizing patients to healthy controls

### ISSUE THREAD

**Issue by hughmt** [pnlbwh/dMRIharmonization#70]
Hi all,

Currently there is a hard requirement to establish a template between the healthy controls of two sites. 

However, this suggests that patient data collected without corresponding healthy controls could not be harmonised to another reference site, with the assumption that doing so may cause some biological signal may be lost. 

Is this something you've considered and are there alternatives to facilitate harmonising a 'patient-only' target dataset to a reference site containing healthy controls?

We spoke with Tashrif recently and he suggested this may be better directed at the broader group of collaborators.

Many thanks in advance for your assistance!

**Comment by yrathi** [comment]
Hi Hugh, Thank you for those comments. Unfortunately, there is no way to harmonize patients from one with controls from a different site, except if you have traveling human subjects acquired on both sites.
