### ISSUE TITLE
Conflicting starting meanFA values for each site depending on the direction of the harmonization. 

### ISSUE THREAD

**Issue by pall75** [pnlbwh/dMRIharmonization#78]
I have DTI data from two different studies A and B  and I want to know the best direction in which to apply the harmonization: either A -> B or B -> A.  

I set up two symmetric harmonization pipelines: One pipeline to harmonise A -> B and another to harmonise B -> A. I used the same training datasets is both cases.

Surprisingly, when I compared the meanFA bar plots after the training each pipeline I got conflicting results. The original meanFA for each group depends on the pipeline that I choose to harmonise the data.

In one direction, the starting meanFA is higher in study A, in the other pipeline the starting meanFA is higher in study B.

The only thing I change between the two pipelines is to swap the “reference" and “target” labels in the harmonisationzation.py commands. 

![PastedGraphic-2](https://user-images.githubusercontent.com/8174306/151341110-230c575e-628d-41dd-8fe8-00fc25c89128.png)

![PastedGraphic-1](https://user-images.githubusercontent.com/8174306/151341150-952dadc8-67c2-481f-aac8-d6b714c83877.png)

Any ideas?

**Comment by yrathi** [comment]
Could you share more details about the data sets? e.g. Do both the sites have the same spatial resolution? How many gradient directions at each site?

**Comment by tashrifbillah** [comment]
Hi Pedro--I haven't set up such symmetric pipelines ever. Here's an idea before further investigation--your should set up the two pipelines in separate input data so nothing from pipeline 1 can collude into pipeline 2. I mean make two sets of directories--`AtoB` with `reference` and target and `BtoA` with `target` and reference. But I understand that you will use the same matching training data. Also use separate `--template` folders. Run again and see if your observation changes.

**Comment by pall75** [comment]
> Could you share more details about the data sets? e.g. Do both the sites have the same spatial resolution? How many gradient directions at each site?

Both data sets were acquired with the same resolution using the same scanner (GE Signa)
The number of gradient directions and the b-values were different. (30 dirs at bval=1200, and 60dirs at bval=1300). 

> Hi Pedro--I haven't set up such symmetric pipelines ever. Here's an idea before further investigation--your should set up the two pipelines in separate input data so nothing from pipeline 1 can collude into pipeline 2. I mean make two sets of directories--`AtoB` with `reference` and target and `BtoA` with `target` and reference. But I understand that you will use the same matching training data. Also use separate `--template` folders. Run again and see if your observation changes.

I used complete separated folders to setup and run each pipeline as you mentioned. The only thing that was common between the pipelines was the git folder containing the dMRIharmonization source code. Should I also download a separate git folder for the source code?

**Comment by yrathi** [comment]
Can you also let us know how many subjects are at each site? 
(a more naive question though -- why are you harmonizing data from the same scanner? or is it same scanner but different site that you are trying to harmonize? -- the later requires harmonization but the former doesnt).

**Comment by pall75** [comment]
> Can you also let us know how many subjects are at each site?
I am training the pipelines on 20 controls from each site. There are another 200 subjects in each study. 

> (a more naive question though -- why are you harmonizing data from the same scanner? or is it same scanner but different site that you are trying to harmonize? -- the later requires harmonization but the former doesnt).
Both studies used the same physical scanner. The reason for doing the harmonization is that we found a significant effect between the controls from both studies (after covariating for age and gender). The effect size was small to medium (partial etta squared = 0.03)

**Comment by yrathi** [comment]
We will be checking the code in the next couple of weeks and will get back to you. Thank you for pointing this out to us.

**Comment by tashrifbillah** [comment]
> I am training the pipelines on 20 controls from each site.

Did you observe the same asymmetry on just the controls?

**Comment by pall75** [comment]
> 

I have only looked at the training data so far (Controls)

**Comment by pall75** [comment]
> Okay how about you dropbox us the 40 NIFTI images so we have the best input to investigate this problem?

I will check the data sharing agreements set up for our project.

**Comment by pall75** [comment]
> @pall75 -- We have been unable to replicate this effect in any of our datasets. So, we are wondering if there is something very specific to your dataset.

I wonder the same thing. It could be that the difference between the meanFA over the skeleton is quite small for my datasets (Δ ~0.01), at least compared to the test data from the Connectom/Prisma  (Δ ~0.12)).

**Comment by tashrifbillah** [comment]
> When I used the fa_skeleton_test.py to produce the stats, the inconsistency between the starting meanFA values depending on the direction disappeared.

Thank you for the observation.

---

> Would it not make sense using a single call to antsApplyTransforms when computing the stats also in debug_fa.py ?

Hi @suheyla2 , Pedro is taking about your [change](https://github.com/pnlbwh/dMRIharmonization/commit/ad58a3b3fdb617bda93e35829bc33d9d9a09549c). I did them in single step before.
