### ISSUE TITLE
Time estimate for template

### ISSUE THREAD

**Issue by nancynewlin-masi** [pnlbwh/dMRIharmonization#83]
I'm running the template step with 6 cpus for 16 subjects. The first round is taking 35+ hours to complete, is this expected or is this a sign I've set it up incorrectly? I can tell that it's running and the job output is updating. 
Here is the step: "Starting ANTS registration on max 6 cpucores. Iteration: 1 of 4"

**Comment by yrathi** [comment]
Yes...this is pretty common. ANTS takes some time to complete.
