### ISSUE TITLE
Pipeline_test.sh values not matching expected

### ISSUE THREAD

**Issue by jenna1029** [pnlbwh/dMRIharmonization#86]
Hi,
I ran the pipeline_test.sh and had no errors other than needing to change nibabel get_data to get_fdata due to the former being deprecated. My output stats values do not match the expected values given in the readme. My output is as follows:

> CONNECTOM,0.6891440894893354,0.010751071660099015
> PRISMA_before,0.8190266398305779,0.0076923292031167425
> PRISMA_after,0.688123684766412,0.00957169487727611

Whereas the readme gives:

> CONNECTOM,0.6799002461759734,0.007886013534889139
> PRISMA_before,0.8016994786111754,0.010304926419301603
> PRISMA_after,0.6763777736686049,0.010977445592601354

I saw this issue was previously addressed here: #7,
however, since the ANTs version I have is now updated to 2.3.0 I wasn't sure if this difference was still to be expected? The harmonized values did shift in the correct direction and come out fairly close to the expected. Thank you.

**Comment by tashrifbillah** [comment]
> The harmonized values did shift in the correct direction and come out fairly close to the expected. Thank you.

Thanks for confirming. Good luck.
